### ISSUE TITLE
Intellisense stopped working

### ISSUE THREAD

**Issue by WoHuy** [andrei-markeev/camljs-console#6]
Hi Andrei,

I'm experiencing the same issue as [this one](https://github.com/andrei-markeev/camljs-console/issues/5) since a few days ago.
I already reinstalled the extension but to no avail.

Wouter

**Comment by andrei-markeev** [comment]
thanks for reporting! I will fix it asap

**Comment by andrei-markeev** [comment]
yes, so basically it was because I accidentally packed wrong version of the TS definition file when uploading new version of extension to Chrome Web Store two days ago.

I now submitted the fix, but it might take some time for it to become available. It seems they now do a manual review every time a change is submitted 😴

**Comment by WoHuy** [comment]
Thanks for your quick reaction – and for providing this wonderful tool!

**Comment by andrei-markeev** [comment]
fixed in 1.0.15
